### PR TITLE
Permalink implemented

### PR DESCRIPTION
**Pull request by teezzan**
Please  Review. It wont merge with dev sha. for some breaking reason

### CODE REVIEW

**Comment by abdulloooh** [comment]
Lmao. It shouldn't be merged if it doesn't merge with dev, it'd cause future issue.


You should have created the Branch our of dev branch. I think you'd need to do that 😃

Or merge with dev locally and try to merge it before you push.

Master is delicate

**Comment by abdulloooh** [comment]
Ok, that's awesome as I just tested it on devdailyayah.

We not need to put the path /permalink/ right?

Also, we would have to scrap the homepage link, the extension that shows surah and ayah has to be enforced.

So, in future if we have an homepage, we can utilize the base address.

OR

We can live the base address and only pass the address with extension that shown surah and ayah into the url of what's shared which can be accessed back. Kindof cool either way!

**Comment by teezzan** [comment]
For now, both of them are the same page. I dont think it matters at all.

**Comment by teezzan** [comment]
If you give params, I'll just check before setting the Ayah and surah. If not, serve normally

**Pull request closed without merging**
