### PR TITLE
readded onesignal sdk files

### PR DESCRIPTION
**Pull request by abdulloooh**
Redeploy
Sorry for omiting a file earlier

I will push an update after

To test. clear your local file under site settings> All sites and clear data for dailyayah... and https://dailyayah...

Then reload the page and enable.

### CODE REVIEW

**Comment by teezzan** [comment]
You're so active today. Wow. ..

**Comment by teezzan** [comment]
Baba do giveaway!!!

**Comment by abdulloooh** [comment]
Lmao. For Git, you are losing a job from prospective employer when they check your git....lol

**Comment by abdulloooh** [comment]
> You're so active today. Wow. ..

lol, Ise laada ni faa

**Pull request merged**
